### ISSUE TITLE
cannot set any parameter in refresher

### ISSUE THREAD

**Issue by KenChenpeng** [hereafter/refreshless#1]
hello
  I bought the refresher and install it in my edge, but I found I couldnot set any paremeter in it.
pls see the attached. 
  it looks other plugin.

**Comment by KenChenpeng** [comment]
![image](https://user-images.githubusercontent.com/49930329/56628179-669bae00-667b-11e9-8a03-46f30869c2e4.png)

**Comment by hereafter** [comment]
Appearantly I forgot to localize the extension properly,  an update is on its way to address this.
Sorry for that.

From your screenshot it looks like you have selected the page text.
The settings itself is hosted as a web page. Please do not select any of the text， or it enters editing mode, which will interferencing with the controls (buttons, edit etc)


Are you able to toggle "开/关" option after deselecting the text (close it and open the settings page again)? If not let me know.

Here is how the extension works

1. goto a web page for example : www.bing.com
2. bring up the "settings
3. Turn on the first switch (开关) to be on 开
4. Please click "Apply"
Now bing.com page will automatically refresh in 5 seconds.

Kindly let me know if the above information resolves your issue. 
and please ignore the localization issues for the moment.

**Comment by hereafter** [comment]
I just patched the localization problem in v1.1.6, it is publishing in windows store,
please update in ~2 days, to see if your problem is fixed

![image](https://github.com/hereafter/refreshless/blob/master/docs/issues/1.png?raw=true)
![image](https://github.com/hereafter/refreshless/blob/master/docs/issues/2.png?raw=true)
![image](https://github.com/hereafter/refreshless/blob/master/docs/issues/3.png?raw=true)

Thanks

**Comment by KenChenpeng** [comment]
Yes I reinstall the plugin. And it works normally this time, Appreciate efficient work from you.


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: hereafter <notifications@github.com>
发送时间: Wednesday, April 24, 2019 6:17:32 PM
收件人: hereafter/refreshless
抄送: KenChenpeng; Author
主题: Re: [hereafter/refreshless] cannot set any parameter in refresher (#1)


I just patched the localization problem in v1.1.6, it is publishing in windows store,
please update in ~2 days, to see if your problem is fixed

<https://github.com/hereafter/refreshless/blob/master/docs/issues/1.png>
<https://github.com/hereafter/refreshless/blob/master/docs/issues/2.png>
<https://github.com/hereafter/refreshless/blob/master/docs/issues/3.png>

Thanks

―
